# XGBoost Regression

gradient.boosting

ensemble learning boosting

objective function
gradient descent
tree pruning

## 1. Train, Test, Fit model

In [4]:
import numpy as np
from sklearn.datasets import make_regression
from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [5]:
X, y = make_regression(n_samples = 1000, n_features = 20, noise = 5)

In [9]:
print(X.shape)
X

(1000, 20)


array([[-0.13185268, -1.3091414 ,  1.07606782, ..., -0.33577917,
         0.21768951, -0.84135582],
       [-0.10202005, -0.71464319, -0.04073432, ..., -1.87277046,
        -1.2741246 ,  0.22428386],
       [-0.25058676, -1.83958353, -0.34233394, ..., -0.06552724,
        -1.82576266,  0.61576526],
       ...,
       [-0.0750012 , -2.24739219,  0.27680851, ..., -1.60072142,
        -0.26125362,  0.31568115],
       [-0.86292658,  0.60412118,  0.8461567 , ..., -0.53898939,
         0.6404716 ,  0.35249924],
       [-1.45410154,  1.17526415,  0.23080182, ...,  1.17155978,
         0.36012091,  0.03757445]])

In [10]:
print(y.shape)
y

(1000,)


array([ 1.68609031e+02,  5.92298297e+01, -5.27974774e+02, -2.94563920e+02,
        9.29984923e+01, -2.47907773e+02, -6.16602713e+01,  4.36671817e+00,
        2.28110068e+01, -1.80963171e+02,  7.67141450e+00, -2.55518420e+02,
        1.70852632e+02, -1.71650562e+01,  8.56707729e+01, -4.63856757e+02,
       -1.11853215e+02,  1.68824677e+02, -6.46395071e+00, -7.91762989e+01,
       -3.19663544e+02, -3.04668545e+02,  8.11099846e+01, -1.82664424e+02,
       -1.98498224e+02, -1.82793147e+02, -1.30108909e+02,  4.51240912e+01,
        1.30292741e+01, -4.43075567e+01, -3.58044380e+01, -1.70228430e+02,
       -4.77915199e+00, -2.41065634e+02,  4.94453218e-01, -1.28054636e+02,
        4.48467240e+01, -1.54096376e+02,  6.82641414e+01, -1.94442806e+02,
       -4.25159668e+01, -6.68196932e+01,  3.89130367e+02,  3.03753473e+02,
       -1.23849505e+02, -4.26468504e+02, -1.85512169e+02,  3.62111542e+02,
       -3.43370498e+02, -5.70230127e+01, -2.69258193e+02,  5.48454498e+01,
       -2.47009898e+02, -

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [13]:
print(X_train.shape, X_test.shape)
print(y_train.shape, y_test.shape)

(800, 20) (200, 20)
(800,) (200,)


In [15]:
model = XGBRegressor()
model.fit(X_train, y_train)

,"objective objective: typing.Union[str, xgboost.sklearn._SklObjWProto, typing.Callable[[typing.Any, typing.Any], typing.Tuple[numpy.ndarray, numpy.ndarray]], NoneType]Specify the learning task and the corresponding learning objective or a customobjective function to be used.For custom objective, see :doc:`/tutorials/custom_metric_obj` and:ref:`custom-obj-metric` for more information, along with the end note forfunction signatures.",'reg:squarederror'
,"base_score base_score: typing.Union[float, typing.List[float], NoneType]The initial prediction score of all instances, global bias.",None
,booster,None
,"callbacks callbacks: typing.Optional[typing.List[xgboost.callback.TrainingCallback]]List of callback functions that are applied at end of each iteration.It is possible to use predefined callbacks by using:ref:`Callback API `... note:: States in callback are not preserved during training, which means callback objects can not be reused for multiple training sessions without reinitialization or deepcopy... code-block:: python for params in parameters_grid: # be sure to (re)initialize the callbacks before each run callbacks = [xgb.callback.LearningRateScheduler(custom_rates)] reg = xgboost.XGBRegressor(**params, callbacks=callbacks) reg.fit(X, y)",None
,colsample_bylevel colsample_bylevel: typing.Optional[float]Subsample ratio of columns for each level.,None
,colsample_bynode colsample_bynode: typing.Optional[float]Subsample ratio of columns for each split.,None
,colsample_bytree colsample_bytree: typing.Optional[float]Subsample ratio of columns when constructing each tree.,None
,"device device: typing.Optional[str].. versionadded:: 2.0.0Device ordinal, available options are `cpu`, `cuda`, and `gpu`.",None
,"early_stopping_rounds early_stopping_rounds: typing.Optional[int].. versionadded:: 1.6.0- Activates early stopping. Validation metric needs to improve at least once in every **early_stopping_rounds** round(s) to continue training. Requires at least one item in **eval_set** in :py:meth:`fit`.- If early stopping occurs, the model will have two additional attributes: :py:attr:`best_score` and :py:attr:`best_iteration`. These are used by the :py:meth:`predict` and :py:meth:`apply` methods to determine the optimal number of trees during inference. If users want to access the full model (including trees built after early stopping), they can specify the `iteration_range` in these inference methods. In addition, other utilities like model plotting can also use the entire model.- If you prefer to discard the trees after `best_iteration`, consider using the callback function :py:class:`xgboost.callback.EarlyStopping`.- If there's more than one item in **eval_set**, the last entry will be used for early stopping. If there's more than one metric in **eval_metric**, the last metric will be used for early stopping.",None
,enable_categorical enable_categorical: boolSee the same parameter of :py:class:`DMatrix` for details.,False
,"eval_metric eval_metric: typing.Union[str, typing.List[typing.Union[str, typing.Callable]], typing.Callable, NoneType].. versionadded:: 1.6.0Metric used for monitoring the training result and early stopping. It can be astring or list of strings as names of predefined metric in XGBoost (See:doc:`/parameter`), one of the metrics in :py:mod:`sklearn.metrics`, or anyother user defined metric that looks like `sklearn.metrics`.If custom objective is also provided, then custom metric should implement thecorresponding reverse link function.Unlike the `scoring` parameter commonly used in scikit-learn, when a callableobject is provided, it's assumed to be a cost function and by default XGBoostwill minimize the result during early stopping.For advanced usage on Early stopping like directly choosing to maximize insteadof minimize, see :py:obj:`xgboost.callback.EarlyStopping`.See :doc:`/tutorials/custom_metric_obj` and :ref:`custom-obj-metric` for moreinformation... code-block:: python from sklearn.datasets import load_diabetes

In [16]:
model.predict(X_test)

array([ -29.378782 ,    5.085841 ,  152.74649  , -250.84886  ,
       -334.2787   ,  -45.752377 , -156.00175  , -188.69334  ,
        -89.77761  , -121.24015  , -114.343666 , -191.64888  ,
        -28.394312 ,   24.880981 ,  -41.518726 , -103.12104  ,
        -63.77064  , -152.27544  ,  -25.488295 ,  -57.96829  ,
        -84.755905 , -132.33475  , -187.7636   ,   78.61338  ,
        236.53796  ,  142.88817  ,   35.146385 ,  -80.74247  ,
        -38.937077 , -181.1223   ,   20.312822 ,  -74.315    ,
          9.305629 ,   50.655937 ,  -91.12366  ,   61.612278 ,
         92.695206 ,  112.68017  ,  181.04733  , -271.38315  ,
       -117.1221   ,  -12.974638 ,  -65.15452  ,  206.11127  ,
         80.583916 ,  -31.422989 ,  149.09464  ,  199.85968  ,
       -130.01884  ,   86.462425 ,   30.42812  , -217.6257   ,
       -130.0752   ,  111.43496  ,  348.43344  ,  -80.55167  ,
        259.78214  ,  135.6061   , -130.04967  ,  -31.840488 ,
        108.79892  , -176.44955  ,   62.589436 ,   55.6

In [17]:
y_pred = model.predict(X_test)

In [19]:
mean_squared_error(y_test, y_pred)

5678.732404168754

## 2. Hyperparameter Tunings

+ n_estimators: number of trees ( more trees -> better fit, too many trees -> overfitting)
+ learning_rate: control contrinute of each tree to the final model ( smaller learning rate -> need more trees)
+ max_depth:(maximum depth of each tree)
+ subsample: fraction of samples used for fitting each tree ( lower values make the algorithm more robust to overfitting, but can increase bias )
+ cosample_bytree: fraction of features used for fitting each tree ( helps in reducting overfitting )
+ gamma: controls the minimum loss reduction required to make the further partion in a tree ( higher values lead to a more conservative model)
+ lamda, alpha: l2 and l1 regularization terms for weights respectively these control complexity of the model

In [21]:
from sklearn.model_selection import GridSearchCV

In [23]:
param_grid = {
    "n_estimators" : [50, 100, 200],
    "learning_rate" : [0.01, 0.1],
    "max_depth" : [3, 7],
    "subsample" : [0.8, 1.0],
    "colsample_bytree" : [0.8, 1.0],
    "gamma" : [0, 0.1]
}

In [24]:
grid_search = GridSearchCV(estimator = XGBRegressor(), param_grid = param_grid, cv = 3, scoring = "neg_mean_squared_error", verbose = 1)

In [26]:
grid_search.fit(X_train, y_train)

Fitting 3 folds for each of 96 candidates, totalling 288 fits


,"estimator estimator: estimator objectThis is assumed to implement the scikit-learn estimator interface.Either estimator needs to provide a ``score`` function,or ``scoring`` must be passed.","XGBRegressor(...ree=None, ...)"
,"param_grid param_grid: dict or list of dictionariesDictionary with parameters names (`str`) as keys and lists ofparameter settings to try as values, or a list of suchdictionaries, in which case the grids spanned by each dictionaryin the list are explored. This enables searching over any sequenceof parameter settings.","{'colsample_bytree': [0.8, 1.0], 'gamma': [0, 0.1], 'learning_rate': [0.01, 0.1], 'max_depth': [3, 7], ...}"
,"scoring scoring: str, callable, list, tuple or dict, default=NoneStrategy to evaluate the performance of the cross-validated model onthe test set.If `scoring` represents a single score, one can use:- a single string (see :ref:`scoring_string_names`);- a callable (see :ref:`scoring_callable`) that returns a single value;- `None`, the `estimator`'s :ref:`default evaluation criterion ` is used.If `scoring` represents multiple scores, one can use:- a list or tuple of unique strings;- a callable returning a dictionary where the keys are the metric names and the values are the metric scores;- a dictionary with metric names as keys and callables as values.See :ref:`multimetric_grid_search` for an example.",'neg_mean_squared_error'
,"n_jobs n_jobs: int, default=NoneNumber of jobs to run in parallel.``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.``-1`` means using all processors. See :term:`Glossary `for more details... versionchanged:: v0.20 `n_jobs` default changed from 1 to None",None
,"refit refit: bool, str, or callable, default=TrueRefit an estimator using the best found parameters on the wholedataset.For multiple metric evaluation, this needs to be a `str` denoting thescorer that would be used to find the best parameters for refittingthe estimator at the end.Where there are considerations other than maximum score inchoosing a best estimator, ``refit`` can be set to a function whichreturns the selected ``best_index_`` given ``cv_results_``. In thatcase, the ``best_estimator_`` and ``best_params_`` will be setaccording to the returned ``best_index_`` while the ``best_score_``attribute will not be available.The refitted estimator is made available at the ``best_estimator_``attribute and permits using ``predict`` directly on this``GridSearchCV`` instance.Also for multiple metric evaluation, the attributes ``best_index_``,``best_score_`` and ``best_params_`` will only be available if``refit`` is set and all of them will be determined w.r.t this specificscorer.See ``scoring`` parameter to know more about multiple metricevaluation.See :ref:`sphx_glr_auto_examples_model_selection_plot_grid_search_digits.py`to see how to design a custom selection strategy using a callablevia `refit`.See :ref:`this example`for an example of how to use ``refit=callable`` to balance modelcomplexity and cross-validated score... versionchanged:: 0.20 Support for callable added.",True
,"cv cv: int, cross-validation generator or an iterable, default=NoneDetermines the cross-validation splitting strategy.Possible inputs for cv are:- None, to use the default 5-fold cross validation,- integer, to specify the number of folds in a `(Stratified)KFold`,- :term:`CV splitter`,- An iterable yielding (train, test) splits as arrays of indices.For integer/None inputs, if the estimator is a classifier and ``y`` iseither binary or multiclass, :class:`StratifiedKFold` is used. In allother cases, :class:`KFold` is used. These splitters are instantiatedwith `shuffle=False` so the splits will be the same across calls.Refer :ref:`User Guide ` for the variouscross-validation strategies that can be used here... versionchanged:: 0.22 ``cv`` default value if None changed from 3-fold to 5-fold.",3
,"verbose verbose: intControls the verbosity: the higher, the more messages.- >1 : the computation time for each fold and p

In [27]:
grid_search.best_params_

{'colsample_bytree': 0.8,
 'gamma': 0,
 'learning_rate': 0.1,
 'max_depth': 3,
 'n_estimators': 200,
 'subsample': 0.8}

In [29]:
y_pred_tuned = grid_search.best_estimator_.predict(X_test)

In [30]:
mean_squared_error(y_test, y_pred_tuned)

1933.6029639717863